apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demoapp
        tier: frontend
    spec:
      containers:
      - name: demoapp
        image: public.ecr.aws/j3d7r7o5/demos:pong
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    app: demoapp
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demoapp
    tier: frontend
